import type {Metadata} from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import React from "react";
import ThemeProvider from "@/components/themes/theme-provider"
import Header from "@/components/features/blocks/Header";
import Footer from "@/components/features/blocks/Footer";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "METO - Accueil",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <Header/>
      {children}
      <Footer/>
    </ThemeProvider>
    </body>
    </html>
  );
}
